apiVersion: v1
kind: ConfigMap
metadata:
  name: bailian-backend-config
  namespace: bailian-prod
  labels:
    app: bailian-backend
data:
  app.conf: |
    [app]
    name = bailian-backend
    version = 1.0.0
    environment = production
    
    [logging]
    level = INFO
    format = json
    
    [monitoring]
    metrics_enabled = true
    health_check_enabled = true
    
    [rate_limiting]
    default_limit = 100
    window_seconds = 60
    
    [security]
    cors_enabled = true
    allowed_origins = https://bailian.example.com
---
apiVersion: v1
kind: Secret
metadata:
  name: bailian-db-secret
  namespace: bailian-prod
  labels:
    app: bailian-backend
type: Opaque
data:
  # Base64 encoded values - replace with actual values
  host: <base64-encoded-db-host>
  port: MzMwNg==  # 3306
  database: YmFpbGlhbg==  # bailian
  username: <base64-encoded-username>
  password: <base64-encoded-password>
---
apiVersion: v1
kind: Secret
metadata:
  name: bailian-redis-secret
  namespace: bailian-prod
  labels:
    app: bailian-backend
type: Opaque
data:
  # Base64 encoded values - replace with actual values
  host: <base64-encoded-redis-host>
  port: NjM3OQ==  # 6379
  password: <base64-encoded-redis-password>
---
apiVersion: v1
kind: Secret
metadata:
  name: bailian-ai-secret
  namespace: bailian-prod
  labels:
    app: bailian-backend
type: Opaque
data:
  # Base64 encoded values - replace with actual API keys
  dashscope-api-key: <base64-encoded-dashscope-api-key>
---
apiVersion: v1
kind: Secret
metadata:
  name: bailian-app-secret
  namespace: bailian-prod
  labels:
    app: bailian-backend
type: Opaque
data:
  # Base64 encoded values - replace with actual secrets
  jwt-secret: <base64-encoded-jwt-secret>
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bailian-backend-sa
  namespace: bailian-prod
  labels:
    app: bailian-backend
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: bailian-backend-role
  namespace: bailian-prod
rules:
- apiGroups: [\"\"]
  resources: [\"configmaps\", \"secrets\"]
  verbs: [\"get\", \"list\", \"watch\"]
- apiGroups: [\"\"]
  resources: [\"pods\"]
  verbs: [\"get\", \"list\"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bailian-backend-binding
  namespace: bailian-prod
subjects:
- kind: ServiceAccount
  name: bailian-backend-sa
  namespace: bailian-prod
roleRef:
  kind: Role
  name: bailian-backend-role
  apiGroup: rbac.authorization.k8s.io