apiVersion: v1
kind: Service
metadata:
  name: bailian-backend-service
  namespace: bailian-prod
  labels:
    app: bailian-backend
    tier: backend
  annotations:
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-spec: \"slb.s2.small\"
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-master-zoneid: \"cn-hangzhou-h\"
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-slave-zoneid: \"cn-hangzhou-i\"
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-force-override-listeners: \"true\"
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 8000
    protocol: TCP
  - name: https
    port: 443
    targetPort: 8000
    protocol: TCP
  selector:
    app: bailian-backend
  sessionAffinity: None
---
apiVersion: v1
kind: Service
metadata:
  name: bailian-backend-internal
  namespace: bailian-prod
  labels:
    app: bailian-backend
    tier: backend
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
  - name: metrics
    port: 8001
    targetPort: 8000
    protocol: TCP
  selector:
    app: bailian-backend